**Name**: Romeo Jose B. Quisto

**SN**: 201907164

**Class**: THQ1

**Task**: Let's apply the Huffman coding! Your end goal is to decode the string of encoded binary messages.

Have fun doing this exercise! 💓

---

# Hidden Messages

From the discussions, we were taught the simple algorithm of Huffman coding. Review that section again to make sure you get this exercise right. 

The objectives are:
* Task 1 - Extract the frequencies of the permuted text given to you.
* Task 2 - Create the Huffman coding function.
* Task 3 - Decode the hidden messages then answer the questions that follow.

# RUN ME BUT DON'T CHANGE ANYTHING

You are allowed to study any of the provided functions. You're not allowed to add more than the given imported packages.

In [ ]:
###############################################
# PLEASE DO NOT CHANGE ANYTHING IN THIS CODE BLOCK!
###############################################

###############################################
# Import useful packages for convenience
###############################################
import math                       # For useful math functions like log of 2
import requests                   # For extracting data saved on git 

###############################################
# Importing data
###############################################
hidden_message  = requests.get('https://raw.githubusercontent.com/rgantonio/CoE161---FileDump/main/hidden_message.txt').text[0:-1]

We can view the randomized text in here. As you can see, it doesn't make sense! However, we can use these information to create our own encoder based on the Huffman coding

In [ ]:
print(hidden_message)

 eo .moersreniiinopees  ngriilsfei mofhhsrwoa eoemso or ryee  eefbonrys nyi arfsdkrthvienc ratmytravatsn ldds ohc uli.rtashggrii t   u  iia i   tphiso hti  rdcmetfnplt. ooa h lu hneh   dsitfebeeatsr aoaisan  hnet c .tdspmdttr e si ef deohontws stau yeto esearnaac  d ct nlnaae otipn eafy  tnheee iwieucpsoviadno   heymali   dan nli m  ptsdmxo i sricsnseta orsono rndhysl. ch mmceolain tpi a sndho bihj atku w ouo leowtoht io wyrkdmsr we  eolu  omnoaew  niao  ufei  t errofetut  feweyctd.ed anmhahvsl ihle siats iro  oiaemn tptsaelrt eud wm ctrtr cai uhrnw  .a mw n anehai h t n mereb motft htvtonot.ehedtsien cr sy  g hx n i  raau phatprts mwno     sba noonttsi ehhdtideddoupenlafhn irtnnonwr tp hgie se harsiwe edd   fet manaeliliotswocnio tci eoieecerenno aeiayeaesthdirwwciu hmofaed nytorjgish ew wenvso ahsgdtded uetoebleahe. lroeunto rfdii d b tsshmsuwnrn ig s ti iei soptbtedc  e. rese  uor edeehts sdah  e inem saretixsn feifhkflebumnwee tcsof  . ue  eoistti aia d yioishtenyetoohebiad stetiwl

# Task 1 - Extracting the frequency distribution

Your goal is to extract the frequency distribution of all the characters present in the text. The characters are all letters from `a` to `z` including `spaces` and `.`. So that's a total of 28 characters in all.

You need to fill in the function `extract_freq_dist(text)` which takes in the text (as a string) and outputs a dictionary with the frequency of each letter. We'll do our Huffman coding in frequency form to avoid floating point errors!



In [ ]:
###############################################
# SANDBOX FOR TESTING
###############################################

freq = extract_freq_dist(hidden_message)

print("Number of characters:", len(freq))
print("Number of spaces:", freq[" "])
print("Number of s:", freq["s"])
print("Number of z:", freq["z"])




###############################################

Number of characters: 28
Number of spaces: 65920
Number of s: 19555
Number of z: 205


In [ ]:
###############################################
# Frequency extraction function
###############################################
def extract_freq_dist(text):
  # Fill in your code here
  placeholder = {}
  ctr = 0
  textlength = len(text)
  while ctr < textlength:
    char = text[ctr]
    if char in placeholder: placeholder[char] += 1
    else: placeholder[char] = 1
    ctr += 1

  return placeholder


# CHECKPOINT (1 PT.)

Let's test out your frequency extractor.

* First, make sure that you only have 28 characters in total. 
* A bit of sanity checking - you should get 65,920 spaces, 19,555 s's, and 205 z's. 

In [ ]:
###############################################
# Extract frequency of the hidden message
# YOU CAN RUN ME BUT DO NOT CHANGE ANYTHING IN HERE
# We'll check your results from here
###############################################

# Extracting frequencies here
freq_dict = extract_freq_dist(hidden_message)

# Quick sanity checking
if(len(freq_dict) == 28):
  print("Good! Correct number of symbols")
else:
  print("Bad! Incorrect number of symbols. Try again")

if(freq_dict[' '] == 65920):
  print("Good! Correct number of spaces")
else:
  print("Bad! Incorrect number of spaces. Try again")

if(freq_dict['s'] == 19555):
  print("Good! Correct number of s")
else:
  print("Bad! Incorrect number of s. Try again")

if(freq_dict['z'] == 205):
  print("Good! Correct number of z")
else:
  print("Bad! Incorrect number of z. Try again")


print(freq_dict)

Good! Correct number of symbols
Good! Correct number of spaces
Good! Correct number of s
Good! Correct number of z
{' ': 65920, 'e': 42491, 'o': 22957, '.': 2764, 'm': 9835, 'r': 18960, 's': 19555, 'n': 22331, 'i': 22467, 'p': 5470, 'g': 5346, 'l': 11710, 'f': 8031, 'h': 18434, 'w': 7060, 'a': 24738, 'y': 7246, 'b': 4545, 'd': 15696, 'k': 1549, 't': 27669, 'v': 3582, 'c': 8306, 'u': 9488, 'x': 620, 'j': 397, 'q': 301, 'z': 205}


# Task 2 - Huffman coding function

This is the exciting part. Fill in the Huffman coding function `huffman_codebook(freq_dict)`. It takes in the frequency distribution you just created and returns another dictionary showing the codebook. Just a reminder, a codebook just shows the mapping of the source symbols to the Huffman codewords.

THIS TABLE IS JUST AN EXAMPLE. IT'S NOT THE CORRECT ONE.

Symbol             | Codewords        | 
-------------------|------------------|
a                  |  1011            |
b                  |  10              |
c                  |  10110           |
d                  |  100             |

The output dictionary should have something like:

`{'a':'1011', 'b':'10', 'c':'10110', 'd':'100'}`

Where the binary code are in strings. We'll use these for decoding hidden messages later.

A few guidelines:
* Make sure the Huffman coding follows the discussion from our Wiki page
* All left branches are tagged with 0s while all right branches are tagged with 1s
* In case of equal probabilities, the deeper tree takes the left path. If they have the same depth, then sort alphabetically
* Actually... Python dictionaries already sort keys first by string length, then by alphabetical order. So you wouldn't worry too much



In [ ]:
###############################################
# Huffman coding function
###############################################
def huffman_codebook(freq_dict):
  # Fill in your code here
  codebook = dict.fromkeys(freq_dict.keys(),'')

  while len(freq_dict) != 1:
    freq_dict = dict(sorted(freq_dict.items(), key=lambda item: item[1])) #sort dictionary in ascending order
    symbols = list(freq_dict.keys()) #create sorted symbols
    freq = list(freq_dict.values()) #create sorted frequencies

    freq_dict[symbols[0]+symbols[1]] = freq[0]+freq[1] #create new item in dictionary

    # left side of tree
    for i in codebook.keys(): #iterate through symbols
      if i in symbols[0]: #check if character is in the left
        codebook[i] = "0" + codebook[i] #add 0

    #right side of tree
    for i in codebook.keys(): #iterate through symbols
      if i in symbols[1]: #check if character is in the right
        codebook[i] = "1" + codebook[i] #add 1

    del freq_dict[symbols[0]] #delete smallest item
    del freq_dict[symbols[1]] #delete 2nd smallest item
    symbols = [] #reset placeholder
    freq = [] #reset placeholder

  return codebook


##############################################
# test
freq_dict = extract_freq_dist(hidden_message)
codebook = huffman_codebook(freq_dict)

# print(freq_dict)
# freq_dict = dict(sorted(freq_dict.items(), key=lambda item: item[1]))
# print(freq_dict)
# symbols = list(freq_dict.keys())
# freq = list(freq_dict.values())
# freq_dict[symbols[0]+symbols[1]] = freq[0]+freq[1]
# del freq_dict[symbols[0]]
# del freq_dict[symbols[1]]
# print(freq_dict)
# print()

# for key in codebook.keys():
#   codebook[key] = "0" + codebook[key]
# print(codebook)
# for key in codebook.keys():
#   codebook[key] = "1" + codebook[key]
# print(codebook)

print(codebook)

{' ': '111', 'e': '010', 'o': '1001', '.': '1100000', 'm': '00101', 'r': '0001', 's': '0011', 'n': '0110', 'i': '0111', 'p': '100001', 'g': '100000', 'l': '10001', 'f': '110011', 'h': '0000', 'w': '110001', 'a': '1010', 'y': '110010', 'b': '1101101', 'd': '11010', 'k': '11000011', 't': '1011', 'v': '1101100', 'c': '110111', 'u': '00100', 'x': '110000100', 'j': '1100001010', 'q': '11000010111', 'z': '11000010110'}


# CHECKPOINT (6 PTS.)

Minimal sanity checking for this part. We'll only check the dictionary values. All or nothing.

If done correctly, you should get:

`' ':'111'`

`'s':'0011'`

`'z':'11000010110'`

In [ ]:
###############################################
# Huffman coding function
# DO NOT CHANGE ANYTHING HERE
###############################################
codebook = huffman_codebook(freq_dict)

# Quick sanity checking
if(codebook[' ']=='111'):
  print("Good! Correct spaces")
else:
  print("Bad! Incorrect spaces. Try again")

if(codebook['s']=='0011'):
  print("Good! Correct s")
else:
  print("Bad! Incorrect s. Try again")

if(codebook['z']=='11000010110'):
  print("Good! Correct z")
else:
  print("Bad! Incorrect z. Try again")

print(codebook)

Good! Correct spaces
Good! Correct s
Good! Correct z
{' ': '111', 'e': '010', 'o': '1001', '.': '1100000', 'm': '00101', 'r': '0001', 's': '0011', 'n': '0110', 'i': '0111', 'p': '100001', 'g': '100000', 'l': '10001', 'f': '110011', 'h': '0000', 'w': '110001', 'a': '1010', 'y': '110010', 'b': '1101101', 'd': '11010', 'k': '11000011', 't': '1011', 'v': '1101100', 'c': '110111', 'u': '00100', 'x': '110000100', 'j': '1100001010', 'q': '11000010111', 'z': '11000010110'}


#Task 3 - Decode the hidden messages

In this task you'll need to create a function `decode_message(decodebook,text)`. 
* The decodebook is simply the swapped keys and values of our codebook. That means all binary values are now keys while all the keys are now the values. We'll do this for you.
*The text argument is a string of binary symbols (e.g.,`1110101001`). The function does not return anything except that it prints the decoded message.



In [ ]:
###############################################
# DO NOT TOUCH. This is the dictionary swapping code.
# Yari ka na pag ginalaw mo ito >:(
###############################################

# Swap key-value terms
decodebook = dict(map(reversed,codebook.items()))

# Check me here
print(decodebook)

{'111': ' ', '010': 'e', '1001': 'o', '1100000': '.', '00101': 'm', '0001': 'r', '0011': 's', '0110': 'n', '0111': 'i', '100001': 'p', '100000': 'g', '10001': 'l', '110011': 'f', '0000': 'h', '110001': 'w', '1010': 'a', '110010': 'y', '1101101': 'b', '11010': 'd', '11000011': 'k', '1011': 't', '1101100': 'v', '110111': 'c', '00100': 'u', '110000100': 'x', '1100001010': 'j', '11000010111': 'q', '11000010110': 'z'}


In [ ]:
###############################################
# Decoding function
###############################################
def decode_message(decodebook,text):
  # Fill in your code here
  message = ''
  check = ''
  ctr = 0
  while ctr < len(text):
    check = check + text[ctr]
    if check in decodebook.keys():
      message += decodebook[check]
      check = ''
    ctr += 1

  return message


# CHECKPOINT - Decoding hidden messages (3 pts.)

Decode the hidden messages. The messages are questions that you need to answer. You can just double click, or highlight the entire text then copy-paste into your decodebook. Make sure to answer thoroughly and write your "solutions"

---
Q1 (2.0 pts. ):

`11010010101101000010010101110110010111101100000101111010110110001000011010100000010111110111100111010011101101000001111000101001101000001011000011110100110110101111101111001110100111011010000011101011001111001101111101110111010011011011111001011000001110101100001001000011000110100111011011110110000100100011001001001000000000100011100101100000`?

Your answer?

**determine the average coding length and coding efficiency. explain thoroughly.**

*The average codelength is **4.178317809081365 bits** while the coding efficiency is **0.9929937483996776**. Using previously built functions info() and entropy(), I created multiple functions to arrive to my answers. First extract_prob_dict() gets the probability dictionary from the frequency dictionary. For L(X), I iterated through the codebook dictionary keys and got the sum of the probability and length of code for each symbol. I got the source entropy H(S) by turning my probability dictionary into a list and calling entropy(). Lastly, the coding efficiency is basically $\frac{H(S)}{L(X)}$. With this, we can observe that using huffman coding will result in an almost maximally efficient coding efficiency.*

In [ ]:
###############################################
# Sandbox for Q1
###############################################

q1_str = "11010010101101000010010101110110010111101100000101111010110110001000011010100000010111110111100111010011101101000001111000101001101000001011000011110100110110101111101111001110100111011010000011101011001111001101111101110111010011011011111001011000001110101100001001000011000110100111011011110110000100100011001001001000000000100011100101100000"

print(decode_message(decodebook,q1_str))

####################################################
# getting functions from prev activities
def info(x):
    if(x == 0):
        return 0
    if(x == 1):
        return 0
    elif(x < 0):
        print("Error! Can't have negative probabilities")
        return 
    elif(x > 1):
        print("Error! Can't have probabilities more than 1")
    else:
        return -1*(math.log(x,2))

def entropy(X):
    ent = 0
    for i in X:
        ent += i*info(i)
    return ent

# get probability dictionary
def extract_prob_dict(freq_dict):
  prob_dict = {}

  for j in freq_dict:
    prob_dict[j] = (freq_dict[j]/sum(freq_dict.values()))

  return prob_dict

prob_dict = extract_prob_dict(freq_dict) # probability dictionary of hidden msg

# get ave codelength L(X)
lx = 0
for i in codebook:
  lx += prob_dict[i]*len(codebook[i]) # prob*length of symbol

# get entropy H(S)
hs = entropy(list(prob_dict.values()))

# get efficiency
n = hs/lx

print("Average code length:", lx)
print("Source Entropy:", hs)
print("Coding efficiency:", n)


determine the average coding length and coding efficiency. explain thoroughly.
Average code length: 4.178317809081365
Source Entropy: 4.149043463244833
Coding efficiency: 0.9929937483996776


---
Q2 (0.5 pts):

`100000011111011000101111011000001011100111001011010000011110110111101110001010111101001101101011110100010010110000100100011111001110011110000011000001100000`


-

`11011011010110110111001011110001010101100111111100110111110000100111101100000111001111101101001110001110000011111000100001100101111011000001011100000101000110001111101000010101111100101001001001110011100111111010101000101011011110001100100100110101100000`

Your answer?

**give the song title and author of...**

**baby lets fix this now. why the hell are you so damn loud.**

*Calm Me Down - Zack Tabudlo*

In [ ]:
###############################################
# Sandbox for Q2
###############################################

q2_str = "100000011111011000101111011000001011100111001011010000011110110111101110001010111101001101101011110100010010110000100100011111001110011110000011000001100000"
q2_str_followup = "11011011010110110111001011110001010101100111111100110111110000100111101100000111001111101101001110001110000011111000100001100101111011000001011100000101000110001111101000010101111100101001001001110011100111111010101000101011011110001100100100110101100000"

print(decode_message(decodebook,q2_str))
print(decode_message(decodebook,q2_str_followup))

give the song title and author of...
baby lets fix this now. why the hell are you so damn loud.


---
Q3 (0.5 pts):

`0011101000101010111101000111111100001011100100010001110110111100101101110110001000010111011010100001111101111000110011100000111110001000010101011111011100111111011000001011100111001011010000011110110111101110001010111101001101101011110100010010110000100100011111001110011` ?

-

`1010101111111010101000001010011011111010101000001010011010000011101110000011110000010101111010011010000011111000011101010111010110001101001101100000111011010000010100110100000111011111001010010110100000111001011010100011010001011010011010000011100000111011011010011111111000011101011101101010100000011101110011101011000001110000101010001011111000011101011101101010111101010111111101001111111100001110100111100011010011010000010100110100000111100001011110001011110110111011011000001111101010100000011110001111100001101000011010111001110101100001101110110111011111000011101011000111110101100101110010110100000101010001101010000010101100000`

Your answer?

**same as question number two. what is the song title and author of**

**at dahan dahang ihiga ang katawan. ngang iyong malamang hindi ka nagiisa. halika na at di kailangang pilitin. dahil para sakin ikaw ay mahalaga.**

*Higa - Arthur Nery*


In [ ]:
###############################################
# Sandbox for Q3
###############################################

q3_str = "0011101000101010111101000111111100001011100100010001110110111100101101110110001000010111011010100001111101111000110011100000111110001000010101011111011100111111011000001011100111001011010000011110110111101110001010111101001101101011110100010010110000100100011111001110011"
q3_str_followup = "1010101111111010101000001010011011111010101000001010011010000011101110000011110000010101111010011010000011111000011101010111010110001101001101100000111011010000010100110100000111011111001010010110100000111001011010100011010001011010011010000011100000111011011010011111111000011101011101101010100000011101110011101011000001110000101010001011111000011101011101101010111101010111111101001111111100001110100111100011010011010000010100110100000111100001011110001011110110111011011000001111101010100000011110001111100001101000011010111001110101100001101110110111011111000011101011000111110101100101110010110100000101010001101010000010101100000"

print(decode_message(decodebook,q3_str))
print(decode_message(decodebook,q3_str_followup))

same as question number two. what is the song title and author of
at dahan dahang ihiga ang katawan. ngang iyong malamang hindi ka nagiisa. halika na at di kailangang pilitin. dahil para sakin ikaw ay mahalaga.


BONUS: QUICK!

`110001011101101111010111100000110111101000110000111100001000101111100001011001011111011011100101111000001001011101101000001111011100111111011100100101110111111101010011011111100011100101110011100011010001100001110111011011001110011011000001010010001110010100000110111101000110000110000011111000010111001000111110111110000111110011011101101101110101111011000001000010101111010000101011110001011100101011110110101101011100111000110011011001111110010110100011100101100000`

In [ ]:
###############################################
# Sandbox for bonus
###############################################

bonus_str = "110001011101101111010111100000110111101000110000111100001000101111100001011001011111011011100101111000001001011101101000001111011100111111011100100101110111111101010011011111100011100101110011100011010001100001110111011011001110011011000001010010001110010100000110111101000110000110000011111000010111001000111110111110000111110011011101101101110101111011000001000010101111010000101011110001011100101011110110101101011100111000110011011001111110010110100011100101100000"

print(decode_message(decodebook,bonus_str))


win a gcash prize by going to cutt dot ly slash infotheorygcash. quick since there are limited slots only.


# HOPE YOU HAD FUN! ❤️